### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by GGM8** [RealPlayerCraft/pythoncalc#1]
On Ubuntu 16.04, whenever i type in `python calc.py` I get this error
`File "Calc.py", line 9
    def print(self):
            ^
SyntaxError: invalid syntax
`
Pls help

**Comment by RealPlayerCraft** [comment]
Try using python 3 instead
In terminal, type in: `python3 calc.py`

**Comment by RealPlayerCraft** [comment]
IDK why I opened it
